- .github/pull_request_template.md
- api/auth.py
- api/initial_data.py
- app.py
The repo did not have a set template that helps the developers to make PRs following the teams conventions.
Added a template that will avail itself when any devs want to submit a pull request.
Open a new PR.
The template will already be there.
> [Chore] Add PR Template

- api/models.py
- Bug in models: Activity and ActivityType have a one to many relationships respectively not many to one.
- Add activity_type_id in Activity model
- Add activities relationship in ActivityType model
- `$ python manage.py test`
> bg(models): fix relationship between activity and activityType

- src/.coveragerc
- src/Pipfile
- src/Pipfile.lock
- src/api/endpoints/activity_types.py
- src/api/endpoints/logged_activities.py
- src/api/models.py
- src/api/utils/marshmallow_schemas.py
- src/app.py
- src/config.py
- src/manage.py
- src/tests/base_test.py
- src/tests/test_activities.py
- src/tests/test_logged_activities.py
- src/tests/test_model.py
A logged in user should be able to view logged activities of any user on the platform
- Add get logged activities marshmallow schema
- Added get logged activities by user ID endpoint
- Add get a user's logged activities tests
At the root of the project directory, run the following command:
$ python manage.py test
> #155736915 Add fetch user's logged activities endpoint

- .dockerignore
- Makefile
- docker/test/Dockerfile
- docker/test/docker-compose.yml
- scripts/test.sh
- scripts/utils.sh
- src/.env.sample
- Currently testing on circle C.I is performed with many commands in the config.yml file under the .circleci folder.
- To run tests a dev may require to shut down the development server and run the tests.
- We containerized the test workflow using docker to automate the testing process. Testing will be done with lesser commands in the config.yml file.
- We created an isolated environment where tests can be run even when the development server is running. 
- Ensure that you have a **.env** file immediately under the src directory locally on your computer. While starting up the tests, docker will use the environment variables inside this file. At the moment of creating this P.R the only variables needed in the .env file are PRIVATE_KEY_TEST and PUBLIC_KEY_TEST. Remove the TEST_DATABASE …
> #156719707 Set up test workflow using docker

- Makefile
- docker/release/Dockerfile
- docker/release/docker-compose.yml
- The application currently is not hosted on GCP yet this is desired. Currently, no workflow exists to containerize the application and have an image that can be pushed to the GCP container registry and use it to run the application.
- We set up a workflow that uses docker to build an image of the application. 
- We then tag the image with the a version name or number(Currently no versioning system has been declared to be used at the time of making this P.R).
-  We publish the image to the Google Cloud Container Registry, or to docker hub.
- Before testing ensure that you have installed docker and docker-compose on your machine.
- Run the commands below on the root of the repository.
-  Build the application by running the command ```make release``` on your terminal. You can confirm that …
> #156729736/#157119553 Set up build,release,publish and tag workflow.

- .gitignore
- src/api/endpoints/activities.py
- src/api/endpoints/roles.py
- src/api/endpoints/societies.py
- src/api/utils/helpers.py
- src/app.py
- src/config.py
- src/run_tests.py
- src/tests/base_test.py
- src/tests/test_activities.py
- src/tests/test_role.py
- The roles were available for use but could not be manipulated through the API.
- Add an endpoint allowing API requests to be made allowing the roles to be manipulated within the system.
- Clone the repository, install the application and attempt to access restricted endpoints.
- Clone the repository, install docker, run `make test` within respository.
> [Feature #156300278] Roles Endpoint 

- src/api/endpoints/activity_types.py
- src/api/endpoints/roles.py
- src/api/endpoints/societies.py
- src/api/utils/helpers.py
- src/api/utils/marshmallow_schemas.py
- src/app.py
- src/tests/test_activity_types.py
- The ActivityType module had very limited functionality in that you could only retrieve the existing activity-types in the Appliactio
- Add functionality to manage activity types.
- Add POST request to create a new activity type.
- Add more functionality to the basic GET request.
- Add PUT request to edit an existing activity type.
- Add DELETE request to delete an existing activity type.
> [Feature #155748085] Manage Activity Types

- .gitignore
- src/api/endpoints/societies.py
- src/api/models.py
- src/api/utils/helpers.py
- src/api/utils/marshmallow_schemas.py
- src/app.py
- src/config.py
- src/manage.py
- src/run_tests.py
- src/tests/base_test.py
- src/tests/test_add_cohort.py
- Add put method to endpoint `/api/v1/societies/cohorts`
- #157803976
- Linking users to their respective societies
- Implement a CLI tool to link Cohorts to their respective societies
- Implement an endpoint to allow admins to add cohorts to socities
- `$ python manage.py tests`
> [feature-157803976] Implement add Cohort to a society

- .github/pull_request_template.md
- src/api/endpoints/activities.py
- src/api/endpoints/logged_activities.py
- src/api/endpoints/roles.py
- src/api/endpoints/societies.py
- src/api/endpoints/users.py
- src/api/models.py
- src/api/utils/auth.py
- src/api/utils/helpers.py
- src/app.py
- src/tests/base_test.py
- src/tests/test_activities.py
- src/tests/test_model.py
- src/tests/test_point_redemption.py
- src/tests/test_role.py
- Society Presidents used to make Redemption requests through Google Forms which is very tedious and prone to error.
- Build a redemption request module that will handle all redemption requests that come in for approval from Success Ops.
- Build a CRUD endpoint that Society Presidents and Success Ops will use to make and approve/reject redemption requests respectively.
> [Feature #158247895] Redemption Requests

- src/.coveragerc
- src/api/endpoints/societies.py
- src/api/models.py
- src/api/utils/helpers.py
- src/api/utils/initial_data.py
- src/api/utils/marshmallow_schemas.py
- src/app.py
- src/tests/test_user_information.py
- #158248467
- Modify enpoint  /api/v1/societies && /api/v1/societies/<string:society_id>
- Implement society schema
- Modify get society information
- Add society schema
- `$ python manage.py tests`
> [feat:(society) #158248467 ] Get society information

- src/api/models.py
- src/api/utils/initial_data.py
- src/manage.py
- src/prod-stag-migrations/versions/7d327a0fb0cf_.py
- src/setup.cfg
- src/tests/base_test.py
- Rename countries to centers
- Pass
- Pass
- python manage.py tests
> ch-fix-incompatible migrations

- src/api/utils/auth.py
- Fellows need to be assigned a default role of `fellow` but this was not the case
- Change role to lowercase
- `$./manage.py tests`
> #159296576 Assigned a default role to fellows

- src/api/utils/auth.py
- src/tests/base_test.py
- Login api token structure updated token
- Tech team changed the structure of the token hence failing login
-
- support both structures from the tech team
-
- `./manage.py tests`
> [bg #158909836] Fix token validation

- src/app.py
- Load balancer needs a health check url to ping app, 
- Add home url: `/ `
- `./manage.py tests`
> [Chore #159395595] Add health check url

- Makefile
- docker/release/Dockerfile
- docker/test/Dockerfile
- scripts/test.sh
- scripts/utils.sh
- src/.env.sample
- src/api/endpoints/redemption_requests.py
- src/api/utils/notifications/README.md
- src/api/utils/notifications/email_notices.py
- src/config.py
- src/requirements.txt
- src/tests/test_notifications.py
- src/tests/test_redemption_requests.py
- src/tests/test_user_information.py
- The stakeholders of the the resources accessed should be alerted when actions are performed.
- Implement asynchronous notifications by email via Mailgun.
> [Feature #158453829] Add Notifications Package

- .circleci/config.yml
- .codeclimate.yml
- Makefile
- docker/database/Dockerfile
- docker/database/docker-compose.yml
- scripts/database.sh
- scripts/upgrade.sh
- scripts/utils.sh
- The process of upgrading the database is manually done. It takes a long process to set up an environment to achieve this activity.
- We created a proxy connection to the database that is instantiated anytime we wish to upgrade the database and close it thereafter.
- Trigger a build on CircleCI in the staging environment.
> #159490406 Automatic upgrading of the database before deploying on staging.

- Pipfile
- src/api/endpoints/logged_activities.py
- src/api/utils/auth.py
- src/api/utils/initial_data.py
- src/app.py
- src/data/cohort_data.csv
- src/manage.py
- src/tests/base_test.py
- src/tests/test_logged_activities.py
- src/tests/test_manage.py
- src/tests/test_role.py
- Implement secretaty review feature
- Add endpoint `/api/v1/logged-activty/verify/<logged-activity-id>`
- Fix https redirection logic
- Clean up url
- `./manage.py tests`
> [ft #158909616] Implement Secretary review logged-activity

- .circleci/config.yml
- .codeclimate.yml
- Makefile
- Pipfile
- docker/database/Dockerfile
- docker/database/docker-compose.yml
- scripts/database.sh
- scripts/upgrade.sh
- scripts/utils.sh
- src/api/endpoints/logged_activities.py
- src/api/utils/auth.py
- src/api/utils/initial_data.py
- src/api/utils/marshmallow_schemas.py
- src/app.py
- src/data/cohort_data.csv
- src/manage.py
- src/tests/base_test.py
- src/tests/test_logged_activities.py
- src/tests/test_manage.py
- src/tests/test_role.py
- The work that has been done needs to be moved from develop to staging.
- N/A
> Move Tested Work from Develop to Staging

- docker/test/Dockerfile
- src/api/endpoints/logged_activities.py
- src/api/models.py
- src/app.py
- src/tests/base_test.py
- src/tests/test_logged_activities.py
- Success-Ops needed functionality to allow them to request more information on a pending LoggedActivity from the logger of the said activity.
- Built an Endpoint to deal with SuccessOps requesting for more information from the logger of the activity
- Tests on the same have been written as well and confirm the functionality as present.
> [Feature] Add functionalty to request info on LoggedActivity

- src/api/endpoints/healthcheck_email/__init__.py
- src/api/endpoints/healthcheck_email/healthcheck_email.py
- src/api/endpoints/healthcheck_email/marshmallow_schema.py
- src/api/services/notifications/helpers.py
- src/api/services/notifications/tasks.py
- src/app.py
- src/requirements.txt
- src/tests/test_notifications.py
- The Previous implementation of the notifications was buggy and inconsistent.
- Replaced the implementation with FlaskMail
- Added an endpoint to test the notifications remotely.
> [Chore] Implement Flask Mail

- src/api/endpoints/activity_types/activity_types.py
- #159885929
- Activity Types POST and PUT endpoints should validate and sanitize payload fields appropriately
- add marshmallow validation to `PUT` request endpoint
> [Chore] Add Validation And Sanitize Activity Types PUT request

- src/api/endpoints/activity_types/activity_types.py
- src/api/endpoints/healthcheck_email/__init__.py
- src/api/endpoints/healthcheck_email/healthcheck_email.py
- src/api/endpoints/healthcheck_email/marshmallow_schema.py
- src/api/services/notifications/helpers.py
- src/api/services/notifications/tasks.py
- src/app.py
- src/requirements.txt
- src/tests/test_notifications.py
> Second Prod Push. Dev To Staging

- Makefile
- README.md
- docker/dev/Dockerfile
- docker/dev/docker-compose.yml
- docker/dev/sandbox.md
- scripts/sandbox.sh
- scripts/wait_for_postgres.sh
- The developers need a local environment that mirrors staging.
- I created part of a docker replica of the infrastructure that is on staging.
e.g.
```
mkdir soc-app
cd soc-app
git clone -b ft-sandbox-159817309 https://github.com/WinstonKamau/andela-societies-backend
git clone -b ft-sandbox-159817309 https://github.com/WinstonKamau/andela-societies-frontend
```
Ensure port 4021, 4022 and 4023 are not running on your machine.
Change directory to the backend
```
cd andela-societies-backend
```
Ensure you have **ALL** your environment variables set in the src/.env file without any quotation marks. 
```
PRIVATE_KEY_TEST={some_value}
PUBLIC_KEY_TEST={some_value}
PUBLIC_KEY={some_value}
DEV_DATABASE={some_value}
DATABASE_URL={some_value}
APP_SETTINGS={some_value}
ANDELA_API_URL={some_value} …
```
> #159817309 Sandbox Environment for The Developers

- src/api/endpoints/logged_activities/approve.py
- Update society associated with the corresponding logged activities.
- After approving the submitted logged-activities, the logged activity point is then added to the corresponding society `total_points` to keep it updated.
`[finishes #160512586]`
> Approve logged activities and update society points

- .gitignore
- src/Dockerfile
- src/Pipfile
- src/api/endpoints/activities/__init__.py
- src/api/endpoints/activity_types/__init__.py
- src/api/endpoints/activity_types/activity_types.py
- src/api/endpoints/logged_activities/__init__.py
- src/api/endpoints/logged_activities/request_info.py
- src/api/endpoints/redemption_requests/__init__.py
- src/api/endpoints/redemption_requests/redemption_numeration.py
- src/api/endpoints/redemption_requests/redemption_points.py
- src/api/endpoints/redemption_requests/redemption_request_funds.py
- src/api/endpoints/roles/__init__.py
- src/api/endpoints/societies/__init__.py
- src/api/endpoints/users/__init__.py
- src/api/utils/helpers.py
- src/app.py
- src/config.py
- src/docker-compose.yml
- src/email_handeler.py
- src/tests/test_logged_activities.py
- Add Email service
- Fix ActivityType Save on edit
> [Feat #160613150] Implement Email service

- src/api/endpoints/activity_types/activity_types.py
- src/api/endpoints/activity_types/marshmallow_schemas.py
- src/api/endpoints/redemption_requests/__init__.py
- src/api/endpoints/redemption_requests/redemption_numeration.py
- src/api/endpoints/redemption_requests/redemption_points.py
- src/api/endpoints/redemption_requests/redemption_request_funds.py
- src/tests/base_test.py
- src/tests/test_redemption_requests.py
- Fix issues from pre-demo call. 
- Fix ActivityType View
- Fix Redemption View
> [Bug #160651542] Fix pre-demo bugs

- src/api/services/auth/auth.py
- src/api/services/auth/helpers.py
- src/api/utils/initial_data.py
- Users without a role caused infinite loading on the frontend client
- Assign a default role to users without roles
- Fix initial data crush bug
> [Bug] Fix infinite loading issue

- src/api/services/auth/auth.py
- src/api/services/auth/helpers.py
- src/api/utils/initial_data.py
- Update production
- Staging is ahead of production
> [Chore] Update production with latest changes
