.circleci/config.yml
docker/release/docker-compose.yml
scripts/deploy.sh

- #157185472
- Update the CircleCI pipeline to include build, release, tag, publish. When this changes are merged to staging or master branch, CircleCI will build the application, if the tests pass, the application will be tagged and pushed to google container registry.
- Currently building and tagging of images workflow is not present in CircleCi, it is being done manually.
- This Changes makes use of CircleCI workflow which are not supported by local builds. This changes can only be tested in CircleCI platform.

[Feature #157185472] Add deployment workflow scripts

---

Makefile
scripts/deploy.sh

- Failed authorization of docker to enable a docker image push to GCP.
- Script passing even if error exists.
- Modified the arguments on the docker command to arguments that suit the version being used on circle C.I.
- Modified the script to exit on an error or if the pipe fails
- Push a commit from the branch called **staging** The push should trigger a deployment build on Circle CI. It is expected that the build will pass and a docker image of the application will be pushed to GCP. Login to the GCP account and view the image that has been pushed under Container Registry.

#157349463 Fix authorization error on docker and modify script

---

src/api/endpoints/roles.py
src/api/utils/initial_data.py
src/app.py
src/tests/base_test.py
src/tests/test_model.py
src/tests/test_role.py

- Success Ops members did not have functionality available to change the executives of the societies.
- Add endpoint to demote the current executives and re-assign the new executives.
- Add functionality to demote the current executives and re-assign the new executives.

[Feature #157931054] Change Society Executives

---

Makefile

- Currently the deployment pipeline deploys an image to the wrong container registry folder on GCP.
- Point the deployment to the right folder.
- Changes to deployment should be visible from now on.

[Bug # 158324319 ] Fix deployment bug

---

src/api/endpoints/activity_types.py
src/api/endpoints/logged_activities.py
src/api/models.py
src/api/utils/helpers.py
src/api/utils/marshmallow_schemas.py
src/tests/base_test.py
src/tests/test_activity_types.py
src/tests/test_logged_activities.py

- #158252789
- Activity types supporting multiple participants
- Activity types supporting multiple participants to automatically request number of participants when logging an activity
- add support multiple participants field to activity type model
- add no of participants to logged activity model
- run database migration and upgrade
- modify affected model's schemas, helper functions and CRUD endpoints to reflect changes
- run `python manage.py tests`

[feat:(logged-activity) #158252789 ] Add number of participants to logged activity

---

src/api/endpoints/redemption_requests.py
src/api/endpoints/societies.py
src/api/models.py
src/app.py
src/run_tests.py
src/tests/base_test.py
src/tests/test_model.py
src/tests/test_point_redemption.py

- The RedemptionRequest Module had a bug where as retrieving RedemptionRequests by society, status would return all RedemptionRequests instead of a filtered list.
- Fix the bug by refining the SQLAlchemy queries

[Chore] Fix Redemption Requests retrieval

---

designs/original.mdj
src/api/endpoints/redemption_requests.py
src/api/endpoints/societies.py
src/api/endpoints/users.py
src/api/models.py
src/api/utils/helpers.py
src/api/utils/initial_data.py
src/api/utils/marshmallow_schemas.py
src/manage.py
src/tests/base_test.py
src/tests/test_model.py
src/tests/test_redemption_requests.py
src/tests/test_user_information.py

- The name "Country" was misleading for the model, seeing as to how it is possible that in future there may be more than center in a single country.
- The RedemptionRequest module was not returning all the required information for the front-end.
- Renamed the Country model to Center.
- Reworked the module to dump the required data through the marshmallow schemas.

[Chore #158811700] Change Country to Center 

---

docker/test/Dockerfile
scripts/test.sh

- The notifications need RabbitMQ to be running in the background as the broker to serve the notifications module.
- Install and run RabbitMQ in the Docker Container

[Chore #158453829] Rabbitmq Dependency for Notifcations

---

src/api/endpoints/logged_activities.py
src/api/utils/auth.py
src/api/utils/helpers.py
src/api/utils/marshmallow_schemas.py
src/tests/base_test.py
src/tests/test_logged_activities.py

- Currently, there isn't an endpoint that serves all logged activities
- Users should not be able to delete logged activities that are no longer in review
- An endpoint `/api/v1/logged-activities` has been created to respond with all logged activities on record.
NB: It accepts a `paginate` query parameter when there is a need to fetch all logged activities without pagination
- A check has been implemented when users attempt to delete logged activities that ensures the logged activity can only be deleted while it's `in review`.
- Clone the repository, install Docker, run `make test` within the repository.
- Run `python run_tests.py` at the root of the `src` directory.

[Feature #158909537/ #157693918] Add fetch all logged activities and update delete logged activity

---

docker/test/Dockerfile
src/api/endpoints/redemption_requests.py
src/config.py

- The notification package was being tested using a static variable.
- The static variable was removed and replaced with a dynamic variable in the event that the CIO changes in the future.

[Chore] Remove static variable

---

src/api/endpoints/logged_activities.py
src/api/utils/marshmallow_schemas.py

- Allow editing of a logged activity without requiring activityId.
- Update without requiring date to be provided.
- Use the logged_activity_id passed in the edit endpoint to update a logged activity.
- Only update date if it is provided in the payload.
- Clone the repository, run the application
- Access the edit logged activity endpoint, and editing should be possible without putting activity id.

#159301341 Edit a logged activity without requiring an activityTypeID

---

src/api/endpoints/redemption_requests.py
src/api/utils/helpers.py
src/app.py
src/tests/base_test.py
src/tests/test_redemption_requests.py

- The finance dept. needed the ability to change the status of a redemption request to completed once the funds have already been sent out.
- They also needed to be notified when a redemption request is approved by the CIO so they can begin processing payment.
- Added notifications that will be emailed to the relevant center for the Redemption Request.
- Added functionality that only Finance members can change the status of a redemption request to completed.

[Feature #159521401] Finance Involvement in Redemption Requests

---

src/api/endpoints/logged_activities.py
src/api/utils/marshmallow_schemas.py
src/app.py
src/tests/base_test.py
src/tests/test_logged_activities.py

- Allow a success-ops user approve multiple logged activities.
- Logged activities are approved in sets of twenty.
- Implement endpoint to allow success-ops to approve multiple logged activities.
- Updated logged activity schema to display `society` and `societyId`.
- Updated logged activity schema to display `date` as `activityDate`.
- Clone the repository, install docker and rabbitmq-app, run `make test` within the repository.

#159427418 Approve multiple logged activities

---

src/api/endpoints/redemption_requests.py
src/api/utils/initial_data.py
src/tests/base_test.py
src/tests/test_add_cohort.py
src/tests/test_model.py
src/tests/test_redemption_requests.py
src/tests/test_user_information.py

- The finance email generator I wrote to customise the email based off of the location of the redemption request was not generating the full email.
- Put the string on the same line so that the whole email address is correctly generated.
- Removed the "str()" as it was unnecessary

[Chore] Fix the finance email generator

---

src/api/endpoints/logged_activities.py
src/app.py
src/tests/test_logged_activities.py

- Allow a success-ops user reject a logged activity.
- Implement endpoint to allow success-ops reject a logged activity.
- Clone the repository, install docker and rabbitmq-app, run `run_tests.py` within the repository.

#159668684 Reject a logged activity

---

src/.coveragerc
src/api/endpoints/activity_types.py
src/api/endpoints/logged_activities.py
src/api/endpoints/redemption_requests.py
src/api/endpoints/roles.py
src/api/models.py
src/api/utils/helpers.py
src/api/utils/marshmallow_schemas.py
src/api/utils/notifications/README_notifications.md
src/api/utils/notifications/email_notices.py
src/api/utils/notifications/task_helpers.py
src/app.py
src/config.py
src/manage.py
src/tests/base_test.py
src/tests/test_activities.py
src/tests/test_activity_types.py
src/tests/test_add_cohort.py
src/tests/test_auth.py
src/tests/test_logged_activities.py
src/tests/test_manage.py
src/tests/test_model.py
src/tests/test_notifications.py
src/tests/test_redemption_requests.py
src/tests/test_role.py
src/tests/test_scheduled_tasks.py
src/tests/test_societies.py
src/tests/test_task_helpers.py
src/tests/test_user_information.py

- Success ops members should get a weekly email notification when there are pending logged activities on the platform.
- Initially, logged activities would get approved but the respective society's total points weren't incremented.
- Celery failed to work without a flask app context.
- There is now a scheduled weekly job that gets the count of all pending logged activities and emails success ops members.
- There's a new line in the _approve logged activities by success ops_ endpoint that increments a society's total points during approval.
- **Other fixes**:
- Set default environment to production
- Prevent creating a redemption request when society has insufficient 
remaining points
- Update notifications package to have its own flask instance for use with celery tasks
- Update and fix …

Add weekly task to email success ops about pending logged activities

---

src/api/endpoints/logged_activities.py
src/api/models.py
src/api/utils/marshmallow_schemas.py
src/app.py
src/tests/test_logged_activities.py

- Logged activities do not contain the owner's photo URL
- The secretary review endpoint is different from what's documented on Apiary
- The frontend currently gets integer values as strings
- Add owner photo to logged activities fields
- Update models serialize method to ignore stringifying integers
- Update Marshmallow Schema fields to match corresponding column types on the DB
- Refactor secretary verify activity tests
- Clone the repository, install Docker, run `make test` within the repository.
- Run the command `python run_tests.py` at the root of the `src` directory

Refactor society secretary approval-rejection endpoint

---

.gitignore
src/api/endpoints/redemption_requests.py
src/tests/test_redemption_requests.py

- Implement email notification to finance with link to view details when redemption request is approved
- Refactor redemption request approval endpoint to send email to finance with link to view details
- Add finance role to GET endpoint `api/v1/societies/redeem/<:redeem_id>` 
- write test
- run `python manage.py tests` from the `src` directory

[ft #159521316] Send Email Notification to Finance When Redemption Request is Approved

---

.circleci/config.yml
scripts/deploy.sh

This P.R. :
* Changes the branch, responsible for deploying to staging, to *develop* branch.
* Changes the format of tagging the docker images. 
- Changed deployment configuration for staging to be deployed from the develop branch.
- Changed the mode of tagging container images to use their respective environments.
Merges made to master an develop branch should deploy to production and staging respectively.

#160418381 Deploy staging from the develop branch 

---

src/api/endpoints/logged_activities/secretary_review.py
src/api/endpoints/redemption_requests/helpers.py
src/api/endpoints/redemption_requests/redemption_points.py
src/tests/base_test.py
src/tests/test_model.py
src/tests/test_redemption_requests.py

- Secretaries should only be able to review logged activities in there societies. 
- Add a check to make sure the secretary belongs to the said society that the logged activity belongs to. 

[Bug #160789232] Fix secretary logged activities view permission bug.
